all: dijkstra help command1 command2

dijkstra:
	g++ dijkstra.cpp -o dijkstra

help:
	./dijkstra -h

command1:
	## Exemplo do comando 1
	./dijkstra -f input -i 1 -l 5

command2:
	## Exemplo do comando 2
	./dijkstra -f input -i 1

clean:
	rm -f dijkstra